Razor/Pages/HallsCinema/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.HallsCinema
{
    public class DeleteModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public DeleteModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        [BindProperty]
        public HallCinema HallCinema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hallcinema = await _context.HallCinemas.FirstOrDefaultAsync(m => m.NumberHall == id);

            if (hallcinema == null)
            {
                return NotFound();
            }
            else
            {
                HallCinema = hallcinema;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hallcinema = await _context.HallCinemas.FindAsync(id);
            if (hallcinema != null)
            {
                HallCinema = hallcinema;
                _context.HallCinemas.Remove(HallCinema);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Razor/Pages/HallsCinema/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.HallsCinema
{
    public class DetailsModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public DetailsModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        public HallCinema HallCinema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hallcinema = await _context.HallCinemas.FirstOrDefaultAsync(m => m.NumberHall == id);
            if (hallcinema == null)
            {
                return NotFound();
            }
            else
            {
                HallCinema = hallcinema;
            }
            return Page();
        }
    }
}

Razor/Pages/HallsCinema/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.HallsCinema
{
    public class EditModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public EditModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        [BindProperty]
        public HallCinema HallCinema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hallcinema =  await _context.HallCinemas.FirstOrDefaultAsync(m => m.NumberHall == id);
            if (hallcinema == null)
            {
                return NotFound();
            }
            HallCinema = hallcinema;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(HallCinema).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HallCinemaExists(HallCinema.NumberHall))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool HallCinemaExists(int id)
        {
            return _context.HallCinemas.Any(e => e.NumberHall == id);
        }
    }
}

Razor/Pages/Movies/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Movies;

public class DeleteModel(MovieContext movieContext) : PageModel
{
    public Movie? Movie { get; set; }
    public async Task OnGetAsync(int id)
    {
        Movie = await movieContext.Movies.FirstAsync(movie => movie.Id == id);
    }

    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {

        var movie = await movieContext.Movies.FirstAsync(movie => movie.Id == id);
        movieContext.Movies.Remove(movie);
        await movieContext.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

Razor/Pages/Movies/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Movies;

public class DetailsModel(MovieContext movieContext, Order order) : PageModel
{
    public Shedule? Shedule { get; set; }
    public async Task OnGetAsync(int id)
    {
        Shedule = await movieContext.Shedules.Include(shedules => shedules.Movie).FirstAsync(shedules => shedules.Id == id);
    }

    public async Task OnPostAddTicket(int id, int i)
    {
        Shedule = await movieContext.Shedules.Include(shedules => shedules.Movie).FirstAsync(shedules => shedules.Id == id);

        var selectedShedule = await movieContext.Shedules.Where(x => x.Id == id).FirstAsync();
        order.ResultCost += selectedShedule.Cost;
        order.Shedules.Add(selectedShedule);
    }

    public object Test()
    {
        return 1;
    }
}

Razor/Pages/Movies/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Movies;

public class EditModel(MovieContext movieContext) : PageModel
{
    [BindProperty]
    public Movie? Movie { get; set; }

    public async Task OnGetAsync(int id)
    {
        Movie = await movieContext.Movies.FirstAsync(movie => movie.Id == id);
    }

    public async Task<IActionResult> OnPostUpdate(int id)
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var updatedMovie = await movieContext.Movies.FirstAsync(movie => movie.Id == id);
        updatedMovie.Title = Movie.Title;
        updatedMovie.URL = Movie.URL;
        updatedMovie.Description = Movie.Description;
        await movieContext.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

Razor/Pages/Shedules/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Shedules
{
    public class DeleteModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public DeleteModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Shedule Shedule { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shedule = await _context.Shedules.FirstOrDefaultAsync(m => m.Id == id);

            if (shedule == null)
            {
                return NotFound();
            }
            else
            {
                Shedule = shedule;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shedule = await _context.Shedules.FindAsync(id);
            if (shedule != null)
            {
                Shedule = shedule;
                _context.Shedules.Remove(Shedule);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Razor/Pages/Shedules/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Shedules
{
    public class DetailsModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public DetailsModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        public Shedule Shedule { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shedule = await _context.Shedules.FirstOrDefaultAsync(m => m.Id == id);
            if (shedule == null)
            {
                return NotFound();
            }
            else
            {
                Shedule = shedule;
            }
            return Page();
        }
    }
}

Razor/Pages/Shedules/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Razor.Data;
using Razor.Model;

namespace Razor.Pages.Shedules
{
    public class EditModel : PageModel
    {
        private readonly Razor.Data.MovieContext _context;

        public EditModel(Razor.Data.MovieContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Shedule Shedule { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shedule =  await _context.Shedules.FirstOrDefaultAsync(m => m.Id == id);
            if (shedule == null)
            {
                return NotFound();
            }
            Shedule = shedule;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Shedule).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SheduleExists(Shedule.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SheduleExists(int id)
        {
            return _context.Shedules.Any(e => e.Id == id);
        }
    }
}

Razor/Pages/Movies/Add.cshtml
@page
@using Razor.Pages.Movies
@model AddModel

<form method="post">
    <div>
        <label>Название фильма</label>
        <input asp-for="Movie.Title" type="text" style="width: 400px" />
        <span asp-validation-for="Movie.Title" class="text-danger"></span>
    </div>
    <div>
        <label>Ссылка на фото</label>
        <input asp-for="Movie.URL" type="text" />
        <span asp-validation-for="Movie.URL" class="text-danger"></span>
    </div>
    <div>
        <label>Описание фильма</label>
        <input asp-for="Movie.Description" type="text" />
        <span asp-validation-for="Movie.Description" class="text-danger"></span>
    </div>
    <input type="submit" />
</form>

Razor/Pages/Movies/Delete.cshtml
@page
@using Razor.Pages.Movies
@model DeleteModel

<div class="container">
    <form method="post">
        <h1>Вы уверены, что хотите удалить фильм @Model.Movie.Title</h1>
        <p>@Model.Movie.Description</p>
        <button type="submit" asp-route-id="@Model.Movie.Id" asp-page-handler="delete" class="btn btn-primary">Удалить</button>
    </form>
</div>

Razor/Pages/Movies/Details.cshtml
@page
@model Razor.Pages.Movies.DetailsModel

@if (Model.Shedule is not null)
{
    <div class="cd__main">
        <div class="container my-5">
            <div class="row">
                <div class="col-md-5">
                    <div class="main-img">
                        <img class="img-fluid" src="@Model.Shedule.Movie.URL" alt="@Model.Shedule.Movie.Title">
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="main-description px-2">
                        <div class="category text-bold">
                            @Model.Shedule.Movie.Title
                        </div>
                        <div class="product-title text-bold my-3">
                            @Model.Shedule.Movie.Description
                        </div>
                        <div class="product-title text-bold my-3">
                            @Model.Shedule.Cost ₽
                        </div>

                        <div class="product-title text-bold my-3">

                            @Model.Shedule.StartFilm.Hour : @Model.Shedule.StartFilm.Minute
                        </div>

                        <h1>Купить билет</h1>
                        <form class="d-flex" method="post">
                            @for (int i = 0; i < 10; i++)
                            {
                                <button 
                                    type="submit"
                                    asp-route-id="@Model.Shedule.Id"
                                    asp-route-i="@i"
                                    asp-page-handler="AddTicket"
                                    onclick="@Model.Test()"
                                    class="btn btn-primary">@i место</button>
                            }
                        </form>
                        <form method="post">
                            
                            
                        </form>
                        <a class="btn btn-primary" asp-page="./Index">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Razor/Pages/Movies/Edit.cshtml
@page
@model Razor.Pages.Movies.EditModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container" style="padding-top: 35px">
    <h1>Добавление фильма к просмотру</h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <input type="hidden" asp-for="Movie.Id" />
                <div class="form-group">
                    <label class="form-label">Название фильма</label>
                    <input asp-for="Movie.Title" type="text" class="form-control">
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <label class="form-label">URL фотографии</label>
                    <input asp-for="Movie.URL" type="text" class="form-control">
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <label class="form-label">Описание фильма</label>
                    <input asp-for="Movie.Description" type="text" class="form-control">
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <label class="form-label">Цена просмотра фильма</label>
                    <input asp-for="Movie.Cost" type="number" class="form-control">
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <a href="Index" class="btn btn-primary">Назад</a>
                    <input type="submit" value="Редактировать" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

Razor/Pages/Movies/Index.cshtml
@page
@using Razor.Pages.Movies
@model IndexModel

<div class="container" style="padding-top: 35px">
    <a asp-page="/Movies/Add" class="btn btn-success">Добавить</a>

    <form method="post">
        <p>Мы показываем фильма с @Model.MinDateMovie по @Model.MaxDateMovie</p>
        <input type="date" asp-for="SearchDateMovie" asp-format="{0:yyyy-MM-ddTHH:mm}" value="@Model.SelectedDateMovie" min="@Model.MinDateMovie" max="@Model.MaxDateMovie">
        <p>Поиск фильма
            <input type="text" asp-for="SearchTitleMovie"  />
            <input type="submit" />
        </p>
    </form>

    <div class="row row-cols-4">
        @if (Model.Shedules is not null)
        {
            @foreach (var shedule in Model.Shedules)
            {
                <div class="col" style="margin-top:20px">
                    <div class="card" style="width: 18rem; height: 350px">
                        <img src="@shedule.Movie.URL" class="card-img-top" alt="@shedule.Movie.Title">
                        <div class="card-body">
                            <h5 class="card-title">@shedule.Movie.Title</h5>
                            <span>@shedule.Cost ₽</span>
                            <h5 class="card-title">@Model.FormateTime(@shedule.StartFilm.Hour) : @Model.FormateTime(@shedule.StartFilm.Minute)</h5>
                            <a asp-page="/Movies/Details" asp-route-id="@shedule.Id" class="btn btn-primary">Купить билет</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>